name = "ExT"
author = "ExTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e812a77a9159d9cfc69e554ca3309b9fc06cac11489dec1c38eae894652d5e9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
