name = "ExT"
author = "ExTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba687b083040d3e3c085d0eb60c8e5b7cf4d8625adbf2068a433fc7477ae589d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
