name = "ExT"
author = "ExTeam"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85c411d03b3d26c0223685e4d89a5bbcdec0392f674c778199a16e2f1b1be34b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
